package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "groupe", catalog = "db_app_muzik")
public class Groupe implements java.io.Serializable {

	private GroupeId id;

	public Groupe() {
	}

	public Groupe(GroupeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idGroupe", column = @Column(name = "id_groupe")),
			@AttributeOverride(name = "nom", column = @Column(name = "Nom", length = 45)),
			@AttributeOverride(name = "mail", column = @Column(name = "mail", length = 100)),
			@AttributeOverride(name = "localisation", column = @Column(name = "localisation", length = 45)),
			@AttributeOverride(name = "biographie", column = @Column(name = "biographie", length = 2000)),
			@AttributeOverride(name = "rencontre", column = @Column(name = "rencontre")) })
	public GroupeId getId() {
		return this.id;
	}

	public void setId(GroupeId id) {
		this.id = id;
	}

}
