package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Instrument generated by hbm2java
 */
@Entity
@Table(name = "instrument", catalog = "db_app_muzik")
public class Instrument implements java.io.Serializable {

	private InstrumentId id;

	public Instrument() {
	}

	public Instrument(InstrumentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idInst", column = @Column(name = "id_inst")),
			@AttributeOverride(name = "nom", column = @Column(name = "nom", length = 45)) })
	public InstrumentId getId() {
		return this.id;
	}

	public void setId(InstrumentId id) {
		this.id = id;
	}

}
