package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InstrumentId generated by hbm2java
 */
@Embeddable
public class InstrumentId implements java.io.Serializable {

	private Integer idInst;
	private String nom;

	public InstrumentId() {
	}

	public InstrumentId(Integer idInst, String nom) {
		this.idInst = idInst;
		this.nom = nom;
	}

	@Column(name = "id_inst")
	public Integer getIdInst() {
		return this.idInst;
	}

	public void setIdInst(Integer idInst) {
		this.idInst = idInst;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InstrumentId))
			return false;
		InstrumentId castOther = (InstrumentId) other;

		return ((this.getIdInst() == castOther.getIdInst()) || (this.getIdInst() != null
				&& castOther.getIdInst() != null && this.getIdInst().equals(castOther.getIdInst())))
				&& ((this.getNom() == castOther.getNom()) || (this.getNom() != null && castOther.getNom() != null
						&& this.getNom().equals(castOther.getNom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdInst() == null ? 0 : this.getIdInst().hashCode());
		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		return result;
	}

}
