package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MusicGroup generated by hbm2java
 */
@Entity
@Table(name = "music_group", catalog = "db_app_muzik")
public class MusicGroup implements java.io.Serializable {

	private MusicGroupId id;

	public MusicGroup() {
	}

	public MusicGroup(MusicGroupId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMaquette", column = @Column(name = "id_maquette")),
			@AttributeOverride(name = "idGroup", column = @Column(name = "id_group")),
			@AttributeOverride(name = "nom", column = @Column(name = "nom", length = 45)),
			@AttributeOverride(name = "musiqueBlob", column = @Column(name = "musique_blob")) })
	public MusicGroupId getId() {
		return this.id;
	}

	public void setId(MusicGroupId id) {
		this.id = id;
	}

}
