package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MusicGroupId generated by hbm2java
 */
@Embeddable
public class MusicGroupId implements java.io.Serializable {

	private Integer idMaquette;
	private Integer idGroup;
	private String nom;
	private byte[] musiqueBlob;

	public MusicGroupId() {
	}

	public MusicGroupId(Integer idMaquette, Integer idGroup, String nom, byte[] musiqueBlob) {
		this.idMaquette = idMaquette;
		this.idGroup = idGroup;
		this.nom = nom;
		this.musiqueBlob = musiqueBlob;
	}

	@Column(name = "id_maquette")
	public Integer getIdMaquette() {
		return this.idMaquette;
	}

	public void setIdMaquette(Integer idMaquette) {
		this.idMaquette = idMaquette;
	}

	@Column(name = "id_group")
	public Integer getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "musique_blob")
	public byte[] getMusiqueBlob() {
		return this.musiqueBlob;
	}

	public void setMusiqueBlob(byte[] musiqueBlob) {
		this.musiqueBlob = musiqueBlob;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MusicGroupId))
			return false;
		MusicGroupId castOther = (MusicGroupId) other;

		return ((this.getIdMaquette() == castOther.getIdMaquette()) || (this.getIdMaquette() != null
				&& castOther.getIdMaquette() != null && this.getIdMaquette().equals(castOther.getIdMaquette())))
				&& ((this.getIdGroup() == castOther.getIdGroup()) || (this.getIdGroup() != null
						&& castOther.getIdGroup() != null && this.getIdGroup().equals(castOther.getIdGroup())))
				&& ((this.getNom() == castOther.getNom()) || (this.getNom() != null && castOther.getNom() != null
						&& this.getNom().equals(castOther.getNom())))
				&& ((this.getMusiqueBlob() == castOther.getMusiqueBlob())
						|| (this.getMusiqueBlob() != null && castOther.getMusiqueBlob() != null
								&& Arrays.equals(this.getMusiqueBlob(), castOther.getMusiqueBlob())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdMaquette() == null ? 0 : this.getIdMaquette().hashCode());
		result = 37 * result + (getIdGroup() == null ? 0 : this.getIdGroup().hashCode());
		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getMusiqueBlob() == null ? 0 : Arrays.hashCode(this.getMusiqueBlob()));
		return result;
	}

}
