package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MusicUserId generated by hbm2java
 */
@Embeddable
public class MusicUserId implements java.io.Serializable {

	private Integer idMusique;
	private Integer idUser;
	private String nom;
	private byte[] musiqueBlob;

	public MusicUserId() {
	}

	public MusicUserId(Integer idMusique, Integer idUser, String nom, byte[] musiqueBlob) {
		this.idMusique = idMusique;
		this.idUser = idUser;
		this.nom = nom;
		this.musiqueBlob = musiqueBlob;
	}

	@Column(name = "id_musique")
	public Integer getIdMusique() {
		return this.idMusique;
	}

	public void setIdMusique(Integer idMusique) {
		this.idMusique = idMusique;
	}

	@Column(name = "id_user")
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "musique_blob")
	public byte[] getMusiqueBlob() {
		return this.musiqueBlob;
	}

	public void setMusiqueBlob(byte[] musiqueBlob) {
		this.musiqueBlob = musiqueBlob;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MusicUserId))
			return false;
		MusicUserId castOther = (MusicUserId) other;

		return ((this.getIdMusique() == castOther.getIdMusique()) || (this.getIdMusique() != null
				&& castOther.getIdMusique() != null && this.getIdMusique().equals(castOther.getIdMusique())))
				&& ((this.getIdUser() == castOther.getIdUser()) || (this.getIdUser() != null
						&& castOther.getIdUser() != null && this.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getNom() == castOther.getNom()) || (this.getNom() != null && castOther.getNom() != null
						&& this.getNom().equals(castOther.getNom())))
				&& ((this.getMusiqueBlob() == castOther.getMusiqueBlob())
						|| (this.getMusiqueBlob() != null && castOther.getMusiqueBlob() != null
								&& Arrays.equals(this.getMusiqueBlob(), castOther.getMusiqueBlob())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdMusique() == null ? 0 : this.getIdMusique().hashCode());
		result = 37 * result + (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getMusiqueBlob() == null ? 0 : Arrays.hashCode(this.getMusiqueBlob()));
		return result;
	}

}
