package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MusicUser generated by hbm2java
 */
@Entity
@Table(name = "music_user", catalog = "db_app_muzik")
public class MusicUser implements java.io.Serializable {

	private MusicUserId id;

	public MusicUser() {
	}

	public MusicUser(MusicUserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMusique", column = @Column(name = "id_musique")),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user")),
			@AttributeOverride(name = "nom", column = @Column(name = "nom", length = 45)),
			@AttributeOverride(name = "musiqueBlob", column = @Column(name = "musique_blob")) })
	public MusicUserId getId() {
		return this.id;
	}

	public void setId(MusicUserId id) {
		this.id = id;
	}

}
