package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId implements java.io.Serializable {

	private Integer idUser;
	private String nom;
	private String mail;
	private String localisation;
	private String biographie;
	private Integer instr1;
	private Integer niveau1;
	private Integer instr2;
	private Integer niveau2;
	private Integer instr3;
	private Integer niveau3;

	public UserId() {
	}

	public UserId(Integer idUser, String nom, String mail, String localisation, String biographie, Integer instr1,
			Integer niveau1, Integer instr2, Integer niveau2, Integer instr3, Integer niveau3) {
		this.idUser = idUser;
		this.nom = nom;
		this.mail = mail;
		this.localisation = localisation;
		this.biographie = biographie;
		this.instr1 = instr1;
		this.niveau1 = niveau1;
		this.instr2 = instr2;
		this.niveau2 = niveau2;
		this.instr3 = instr3;
		this.niveau3 = niveau3;
	}

	@Column(name = "id_user")
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "Nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "mail", length = 100)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "localisation", length = 45)
	public String getLocalisation() {
		return this.localisation;
	}

	public void setLocalisation(String localisation) {
		this.localisation = localisation;
	}

	@Column(name = "biographie", length = 2000)
	public String getBiographie() {
		return this.biographie;
	}

	public void setBiographie(String biographie) {
		this.biographie = biographie;
	}

	@Column(name = "instr1")
	public Integer getInstr1() {
		return this.instr1;
	}

	public void setInstr1(Integer instr1) {
		this.instr1 = instr1;
	}

	@Column(name = "niveau1")
	public Integer getNiveau1() {
		return this.niveau1;
	}

	public void setNiveau1(Integer niveau1) {
		this.niveau1 = niveau1;
	}

	@Column(name = "instr2")
	public Integer getInstr2() {
		return this.instr2;
	}

	public void setInstr2(Integer instr2) {
		this.instr2 = instr2;
	}

	@Column(name = "niveau2")
	public Integer getNiveau2() {
		return this.niveau2;
	}

	public void setNiveau2(Integer niveau2) {
		this.niveau2 = niveau2;
	}

	@Column(name = "instr3")
	public Integer getInstr3() {
		return this.instr3;
	}

	public void setInstr3(Integer instr3) {
		this.instr3 = instr3;
	}

	@Column(name = "niveau3")
	public Integer getNiveau3() {
		return this.niveau3;
	}

	public void setNiveau3(Integer niveau3) {
		this.niveau3 = niveau3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this.getIdUser() != null
				&& castOther.getIdUser() != null && this.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getNom() == castOther.getNom()) || (this.getNom() != null && castOther.getNom() != null
						&& this.getNom().equals(castOther.getNom())))
				&& ((this.getMail() == castOther.getMail()) || (this.getMail() != null && castOther.getMail() != null
						&& this.getMail().equals(castOther.getMail())))
				&& ((this.getLocalisation() == castOther.getLocalisation())
						|| (this.getLocalisation() != null && castOther.getLocalisation() != null
								&& this.getLocalisation().equals(castOther.getLocalisation())))
				&& ((this.getBiographie() == castOther.getBiographie()) || (this.getBiographie() != null
						&& castOther.getBiographie() != null && this.getBiographie().equals(castOther.getBiographie())))
				&& ((this.getInstr1() == castOther.getInstr1()) || (this.getInstr1() != null
						&& castOther.getInstr1() != null && this.getInstr1().equals(castOther.getInstr1())))
				&& ((this.getNiveau1() == castOther.getNiveau1()) || (this.getNiveau1() != null
						&& castOther.getNiveau1() != null && this.getNiveau1().equals(castOther.getNiveau1())))
				&& ((this.getInstr2() == castOther.getInstr2()) || (this.getInstr2() != null
						&& castOther.getInstr2() != null && this.getInstr2().equals(castOther.getInstr2())))
				&& ((this.getNiveau2() == castOther.getNiveau2()) || (this.getNiveau2() != null
						&& castOther.getNiveau2() != null && this.getNiveau2().equals(castOther.getNiveau2())))
				&& ((this.getInstr3() == castOther.getInstr3()) || (this.getInstr3() != null
						&& castOther.getInstr3() != null && this.getInstr3().equals(castOther.getInstr3())))
				&& ((this.getNiveau3() == castOther.getNiveau3()) || (this.getNiveau3() != null
						&& castOther.getNiveau3() != null && this.getNiveau3().equals(castOther.getNiveau3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getMail() == null ? 0 : this.getMail().hashCode());
		result = 37 * result + (getLocalisation() == null ? 0 : this.getLocalisation().hashCode());
		result = 37 * result + (getBiographie() == null ? 0 : this.getBiographie().hashCode());
		result = 37 * result + (getInstr1() == null ? 0 : this.getInstr1().hashCode());
		result = 37 * result + (getNiveau1() == null ? 0 : this.getNiveau1().hashCode());
		result = 37 * result + (getInstr2() == null ? 0 : this.getInstr2().hashCode());
		result = 37 * result + (getNiveau2() == null ? 0 : this.getNiveau2().hashCode());
		result = 37 * result + (getInstr3() == null ? 0 : this.getInstr3().hashCode());
		result = 37 * result + (getNiveau3() == null ? 0 : this.getNiveau3().hashCode());
		return result;
	}

}
