package fr.formation.inti.entity;
// Generated 6 f�vr. 2023 � 09:29:17 by Hibernate Tools 5.1.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "db_app_muzik")
public class User implements java.io.Serializable {

	private UserId id;

	public User() {
	}

	public User(UserId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idUser", column = @Column(name = "id_user")),
			@AttributeOverride(name = "nom", column = @Column(name = "Nom", length = 45)),
			@AttributeOverride(name = "mail", column = @Column(name = "mail", length = 100)),
			@AttributeOverride(name = "localisation", column = @Column(name = "localisation", length = 45)),
			@AttributeOverride(name = "biographie", column = @Column(name = "biographie", length = 2000)),
			@AttributeOverride(name = "instr1", column = @Column(name = "instr1")),
			@AttributeOverride(name = "niveau1", column = @Column(name = "niveau1")),
			@AttributeOverride(name = "instr2", column = @Column(name = "instr2")),
			@AttributeOverride(name = "niveau2", column = @Column(name = "niveau2")),
			@AttributeOverride(name = "instr3", column = @Column(name = "instr3")),
			@AttributeOverride(name = "niveau3", column = @Column(name = "niveau3")) })
	public UserId getId() {
		return this.id;
	}

	public void setId(UserId id) {
		this.id = id;
	}

}
